### ISSUE TITLE
Add aspect ratio setting to virtual screen?

### ISSUE THREAD

**Issue by penfold42** [redPanther/hypersim#1]
it appears to be 4:3 - can this be configured to support 16:9 ?

or maybe any arbitrary aspect ratio at all?

**Comment by redPanther** [comment]
leds are scaled into an 800x600 window. I can make this size settings adjustable. would this fullfill your needs?

**Comment by penfold42** [comment]
That would be great - maybe just add an aspect ratio drop down (4:3 or 16:9) that  flip to 1067x600

**Comment by redPanther** [comment]
... its implemented, can you test it?

(when opening hyperion config, ratio is set to 16:9 by default - because most users will have 16:9 for tv ambilight application)

**Comment by penfold42** [comment]
It seems to work great !

Thanks !

What does the led size option do ?

On Windows it doesn't appear to do anything from my quick play with it

**Comment by redPanther** [comment]
ledsize is for led layouts in opc format. try the demo config (opc_xy the cricle.json file)
hypersim is not only for hyperion testing, it is also a testing server for fadecandy or OPC clients in general

**Comment by penfold42** [comment]
Aha !

**Comment by redPanther** [comment]
there are lots of todos for making ui clean and understandable. I will make it better from time to time. Any help is appreciated.
